name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3da2a4abefeb06c5ca47d58ad2a95f67815f051d282c73957111b55d36f8522"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
