name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "199a2f621adf1f9c332ef2e21aa2f1cf279ac51a1ceb34e7b829f414eef354c8"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
