name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f2bc126a58794e668a953b87244dcabc70e357a22bcb9fee8e32a311b9f2871"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
