name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a8b6ede4096b5af7ed6cb1c591a1fd473382e28f0a01e787ac613381a985dc7"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
