name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efd01a9613fba02005b6690d4d1291ad5a3288bb79ee4c5377d7d7ce757ba34f"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
