name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a830f2b7085b6534e77b3e971a648663793a5d81affb7638fbaf316c0114bd"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
