name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b863315547d975d415a17b4dd03d231f02c3466edf958fb5adac04b7d979d8f0"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
