name = "Pot and Kettle"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8e2a6ccee838ec07eef5511445606142f0c82b9e4a76f9e67b510f45f0f8950"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
